[theme]
base = "dark"
# Krwista czerwień dla przycisków akcji
primaryColor = "#D32F2F"
# Prawdziwa, głęboka czerń (jak w nocy)
backgroundColor = "#000000"
# Ciemny grafit dla kontrastu (zakładki, pola tekstowe)
secondaryBackgroundColor = "#121212"
# Czysta biel dla idealnej czytelności tekstu
textColor = "#FFFFFF"
font = "sans serif"